CREATE TABLE IF NOT EXISTS public.comunicados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensaje TEXT NOT NULL,
    enviado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Permisos de lectura y escritura
ALTER TABLE public.comunicados ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir todo en comunicados" ON public.comunicados
    FOR ALL
    USING (true)
    WITH CHECK (true);
